- name: Start minio
  systemd:
    name: minio
    state: started
    daemon_reload: yes

- name: wait for minio to start
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    port: "{{ minio_port }}"
    timeout: 50

- name: register minio to consul
  uri:
    url: "http://{{ groups['consul'][0] }}:{{ consul_port }}/v1/agent/service/register"
    method: PUT
    body_format: json
    body:
      Name: minio
      ID: "minio_{{ inventory_hostname }}"
      Address: "{{ inventory_hostname }}"
      Port: "{{ minio_port }}"
      Check:
        DeregisterCriticalServiceAfter: "5m"
        TCP: "{{ inventory_hostname }}:{{ minio_port }}"
        Interval: "5s"
